spring:
  application:
    name: dairy-farm-management

  datasource:
    url: jdbc:mysql://localhost:3306/dairy_farm_management
    username: root
    password: Gapnsk@5
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
